#!/bin/zsh

thiscommand=`basename $0`
if [ $# -eq 0 ]
then
  echo "Usage: $thiscommand (executable_name) [...OPTIONS]"
  exit 1
fi

cmd=${@:1}
args=${@:2}

# Find the processes that match the cmd, but aren't search processes or this process
processes=$(ps ax | rg "$cmd" | rg -v rg | rg -v $thiscommand)

echo $processes
# If a process is already running that matches the command, focus its window
if [ ! -z $processes ]
then
  local psaux_pids="$(echo $processes | awk '{print $1}')"

  # If any pid matches, get the associated wm_hex and focus the window
  while IFS= read -r pid; do
    local wm_hex="$(wmctrl -lp | awk -vpid=$pid '$3==pid {print $1; exit}')"
    if [ ! -z $wm_hex ]
    then
      wmctrl -ia $wm_hex
      break
    fi
  done <<< "$psaux_pids"
else
  # Otherwise, start the command
  ((echo $args | xargs $1&) && (sleep 1))
fi

exit 0
